### PR TITLE
Add ability to control permissions and other tidbits

### PR DESCRIPTION
**Pull request by flashmob**
Thanks for the maildir package!
Here are some small additions:
- close file after writing & Fsync
- Add support for writing with permissions and ownerships (chmod / chown)
- Update tests to test permissions
- Update readme (kept old New() function for compatibility)

### CODE REVIEW

**Comment by sloonz** [comment]
Thanks for your contribution ! It looks like mostly good, but there’s two points I would like to see done differently : 

1.

```
+	// replace directory bits with 07, preserve u+g bits
+	dirPerm := perm
+	if perm>>6 != 07 {
+		dirPerm = os.FileMode(0077&perm | 0700)
+	}
```

The resulting directory permissions are really suprising from an user point of view : this means that requesting `640` permissions for the files will result in `740` permissions for the directory. I think Ansible has a more sensible approach here : directory permissions are file permissions with `x` bits set equals to `r` bits. It is easily done that way : `dirPerms := os.FileMode(perm | ((perm&0444)>>2))`

Related : please don’t set `x` bit for files as the default in the `New()` constructor. Generating executable mail files is probably a good way to end up murdered by an angry sysadmin ;)

2.

```
+	if uid > 0 && gid > 0 {
+		return os.Chown(path, uid, gid)
+	}
```

Please use uid=-1 and gid=-1 to signify no change (that’s the semantic for `chown` in the libc, and it’s also the (alas) undocumented behavior of `os.Chown` of Go on Linux) : `0` is for root. And use `||` to make it possible to change the group without changing the user.

**Comment by flashmob** [comment]
Thanks for the feedback

Thanks for the info about -1 semantic, good to know there's a convention! 

Right, the x bits are set for directories only, not files. No files are executable.

Regarding the x behaviour, all it's trying to do is the following command:

chmod u+x dirname  

The ansible way seems to be messing up and adding x to all other parts, i.e

chmod +x dirname

Go playground here https://play.golang.org/p/9RD_h3bqUg

**Comment by flashmob** [comment]
So the last commit documents things better which should be a "Caveat Emptor", and uses the -1 convention as per your feedback! 

Here is the project where your package is used: https://github.com/flashmob/maildiranasaurus

Now looking for an mbox package. Have you seen any good ones around?

**Comment by flashmob** [comment]
Just made a correction. 
- Toned down the default file permission to 0600 
- Simplified the setting of u+x

Question:

Should we support the sticky bit? For my project, the sticky bit would be out of scope. But if you want, maybe the sticky bit could be set automatically after changing ownership? Or a boolean flag in NewWithPerm function?

**Comment by flashmob** [comment]
btw, new playground here showing the sticky bit https://play.golang.org/p/rAp94FkdGs

**Comment by sloonz** [comment]
> The ansible way seems to be messing up and adding x to all other parts, i.e

Yeah, that’s the goal. For directories, we generally want to add the x bit to any part that has the r bit, so for example 640 will be translated to 750. We don’t want 740 because read permissions without traversal permissions, although technically possible, is seldom the desired outcome, and we obviously don’t want 751 either.

> Toned down the default file permission to 0600

Good idea !

> Should we support the sticky bit? For my project, the sticky bit would be out of scope. But if you want, maybe the sticky bit could be set automatically after changing ownership? Or a boolean flag in NewWithPerm function?

I don’t think it’s necessary. That’s a quite specific usage, and since we return the path in the Child() method (and Path is public anyway) the user can just use it for more specialized usage.

> Now looking for an mbox package. Have you seen any good ones around?

No I don’t. ProtonMail has https://github.com/ProtonMail/go-mbox/blob/master/writer.go, but they don’t seems to escape correctly mails containing ">From " or ">>From "...

OTOH, I’m not sure a library is necessary for that. Untested: 

```
// sender is one word, without spaces or tabs; it is usually the envelope sender of the message.
// date is the delivery date of the message.  It always contains exactly 24 characters in asctime format
// message is assumed to be in the RFC822 format
// mbox is the mbox file, opened in append mode
func WriteToMbox(sender, date, message string, mbox io.Writer) {
    mbox.WriteString("\r\n")
    mbox.WriteString("From " + sender + " " + date + "\r\n")
    mbox.WriteString(regexp.MustCompile("(?m)^>*From ").ReplaceAllString(message, ">$0"))
    mbox.WriteString("\r\n\r\n")
}
```

**Comment by flashmob** [comment]
Thanks for the review and code snippet.
Yeah, mbox is simple enough. 🙂
We'll, how about we leave the code like this, and let the user of your package decide whenever they want the ansible way or not. The current code does only the minimal thing, which is to set the x on the user octet only, just to ensure that it will work in when the default perms are now 0600. Otherwise tests fail because they can't remove the directory .
Thanks again for your package.

**Comment by flashmob** [comment]
Accidentally closed it, sorry

**Comment by flashmob** [comment]
Could u hold on a little with merge. Would like to test a little more. Thanks.

**Comment by sloonz** [comment]
> We'll, how about we leave the code like this, and let the user of your package decide whenever they want the ansible way or not. The current code does only the minimal thing, which is to set the x on the user octet only, just to ensure that it will work in when the default perms are now 0600

Yes, the user can change permissions after the fact, but the ansible one (ie setting x bit = r bit) should really be the default. Unix systems, directory permissions with r bit ≠ x bit are the exception rather than the rule. Generating such directories without any good reason doesn’t seems reasonable.

**Comment by flashmob** [comment]
Understand your point fully now.
Ansible way it will be.
Will update PR soon.

**Comment by flashmob** [comment]
Hi @sloonz 

Thanks for waiting! Those are the final changes now and it's ready to merge.

A fuzz test has been prepared and run on the encode function.

The test passed without any crashes after running for an hour or so :+1: 
This test was placed in a separate branch since it requires to build in a different way with some extra files, so those who import the package will not get these files.
See https://github.com/flashmob/go-maildir/tree/fuzztest

Small refactoring was done to Child func so that the fuzzer could look at the result of the encode func without creating the files.

Here is what was added since the last push:

- moved the getting of the pid to a package var, since it only needs to be read once
- added a test to make sure that pid is included in file names
- directory permissions: an additional chmod +x will be added for every r permission in user/group/other
- updated tests for new behavior
- updated readme to document new behaviour

**Comment by sloonz** [comment]
Looks good ! I’ll try your master branch on https://github.com/sloonz/ua for a few day just to be extra-sure, and then I’ll merge it.

Do you mind if I squash the git history during the merge ?

**Comment by flashmob** [comment]
Yes, squash and merge would be fine.

**Comment by sloonz** [comment]
Merged, thanks for your contribution !

**Comment by flashmob** [comment]
Hi @sloonz - it looks like you may have accidentally closed it instead of merging?

**Comment by flashmob** [comment]
Sorry, never mind - the code is there... Will delete my fork and point to yours! Have a good day.

**Pull request closed without merging**
